version: "3.8"

services:
  # Java backend
  content_api:
    container_name: content_api
    build:
      context: ./content_api/src/main/docker
      dockerfile: Dockerfile.dev
    ports:
      - "5000:8080"
      - "5005:5005"
    restart: always
    volumes:
      - ./content_api:/work/
    working_dir: /work/
    command: ["./mvnw", "quarkus:dev"]
    depends_on:
      - db

  # PostgreSQL DB
  db:
    container_name: db
    image: postgres:17
    ports:
      - "5432:5432"            
    volumes:
      - ./content_api/volumes/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6

  # PGAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./content_api/volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    user: '$UID:$GID'

  # Frontend (Next.js)        
  frontend:
    container_name: lunarflow_frontend
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    restart: always
    command: ["npm", "run", "dev"]
